services:
  api:
    volumes:
      - ../src:/app/src:ro
    command:
      - uvicorn
      - fastapi_template.entrypoints.fastapi.app:app
      - --reload
      - --host
      - 0.0.0.0
      - --port
      - "8000"

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
